export function getAchievements({
    totalCompletedHistory,
    bestStreak,
    level,
    xp,
    habits,
}) {
    return [
        {
            id: "1",
            title: "Primer Paso",
            description: "Completar tu primer hábito",
            icon: "star",
            badgeBg: ["#eab308", "#facc15"],
            unlocked: totalCompletedHistory >= 1,
            progress: totalCompletedHistory,
            goal: 1,
        },
        {
            id: "2",
            title: "Racha de Fuego",
            description: "Alcanzar una racha de 7 días",
            icon: "flame",
            badgeBg: ["#ea580c", "#f97316"],
            unlocked: bestStreak >= 7,
            progress: bestStreak,
            goal: 7,
        },
        {
            id: "3",
            title: "Constancia Total",
            description: "Tener 5 hábitos activos",
            icon: "list",
            badgeBg: ["#06b6d4", "#3b82f6"],
            unlocked: habits.length >= 5,
            progress: habits.length,
            goal: 5,
        },
        {
            id: "4",
            title: "Maestro",
            description: "Alcanzar el nivel 5",
            icon: "ribbon",
            badgeBg: ["#a855f7", "#ec4899"],
            unlocked: level >= 5,
            progress: level,
            goal: 5,
        },
        {
            id: "5",
            title: "Campeón",
            description: "Llegar a una racha de 30 días",
            icon: "trophy",
            badgeBg: ["#f59e0b", "#fbbf24"],
            unlocked: bestStreak >= 30,
            progress: bestStreak,
            goal: 30,
        },
        {
            id: "6",
            title: "Objetivo Cumplido",
            description: "Acumular 1000 XP",
            icon: "medal",
            badgeBg: ["#10b981", "#22c55e"],
            unlocked: xp >= 1000,
            progress: xp,
            goal: 1000,
        },
    ];
}